repos:
  # Allgemeine Dateisystem-Checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      # Optional
      - id: check-json
      - id: check-toml

  - repo: local
    hooks:
      - id: make-check
        name: Run make check
        entry: make check
        language: system
