ARG PYTHON_VERSION=3.12

FROM python:${PYTHON_VERSION}-slim-bookworm

RUN apt-get update && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*

RUN git config --global --add safe.directory /app

RUN adduser --system --group --uid 1000 --shell /bin/bash appuser

ENV POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=false \
    POETRY_NO_INTERACTION=1

RUN curl -sSL https://install.python-poetry.org | python - --version 1.8.3

ENV PATH="${POETRY_HOME}/bin:${PATH}"

RUN chown -R appuser:appuser "${POETRY_HOME}"

WORKDIR /app

RUN chown -R appuser:appuser /app

USER appuser

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root --sync --with dev

CMD ["bash"]